# Propriedades da aplicacao Spring Boot
spring:
  main:
    banner-mode: console
  application:
    name: dev-specification
  h2:
    console:
      enabled: true
      path: /h2-console
      
# Dados exibidos no endpoint "info" do Actuator
info:
  app:
    groupId: "@project.groupId@"
    artifactId: "@project.artifactId@"
    version: "@project.version@"
    java.version: "@java.version@"
    
# Configuracao da aplicacao
application:
  backing-services:
    database:
      url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1
      username: sa
      password:
      pool-size: 20
      driver-class-name: org.h2.Driver

# Server
server:
  port: 8080
  servlet:
    context-path: /dev-specification

# Configuracao do banco de dados
spring.jpa:
  show-sql: true
  generate-ddl: false
  database: H2
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      
# Configuracao do Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true